import "opentui-spinner/react";
import { useTheme } from "../../hooks";
import { Mode } from "@koda-arc/database/enums";

export const SPINNER_NAMES = [
  "dots",
  "dots2",
  "dots3",
  "dots4",
  "dots5",
  "dots6",
  "dots7",
  "dots8",
  "dots9",
  "dots10",
  "dots11",
  "dots12",
  "dots13",
  "dots14",
  "dots8Bit",
  "dotsCircle",
  "sand",
  "line",
  "line2",
  "rollingLine",
  "pipe",
  "simpleDots",
  "simpleDotsScrolling",
  "star",
  "star2",
  "flip",
  "hamburger",
  "growVertical",
  "growHorizontal",
  "balloon",
  "balloon2",
  "noise",
  "bounce",
  "boxBounce",
  "boxBounce2",
  "triangle",
  "binary",
  "arc",
  "circle",
  "squareCorners",
  "circleQuarters",
  "circleHalves",
  "squish",
  "toggle",
  "toggle2",
  "toggle3",
  "toggle4",
  "toggle5",
  "toggle6",
  "toggle7",
  "toggle8",
  "toggle9",
  "toggle10",
  "toggle11",
  "toggle12",
  "toggle13",
  "arrow",
  "arrow2",
  "arrow3",
  "bouncingBar",
  "bouncingBall",
  "smiley",
  "monkey",
  "hearts",
  "clock",
  "earth",
  "material",
  "moon",
  "runner",
  "pong",
  "shark",
  "dqpb",
  "weather",
  "christmas",
  "grenade",
  "point",
  "layer",
  "betaWave",
  "fingerDance",
  "fistBump",
  "soccerHeader",
  "mindblown",
  "speaker",
  "orangePulse",
  "bluePulse",
  "orangeBluePulse",
  "timeTravel",
  "aesthetic",
  "dwarfFortress",
  "fish",
];

type Props = {
  mode?: Mode;
};

export function Spinner({ mode = Mode.BUILD }: Props) {
  const { colors, currentSpinner } = useTheme();
  const activeColor =
    mode === Mode.PLAN ? colors.agent.plan : colors.agent.idle;

  return (
    <spinner name={(currentSpinner || "arc") as any} color={activeColor} />
  );
}
